// member

var member = (function(){
	var init = function(){onCreate();};
	var setContentView = function(){
		$('#pub_header').on('click','#m_management',function(){
		    $('#account-item').html(ACCOUNT);
		    $('#dashboard-item').html(DASHBOARD);
		    $('#inbox-item').html(INBOX);
		    $('#your-trips-item').html(TRIPS);
		    $('#user-profile-item').html(EDIT);
		    $('#booking-item').html(BOOKING);
		    $('#go_admin').html(ADMIN);
	      });
	};
	var onCreate = function(){
		setContentView();
	};
	return {init : init};
})();


var nav = (function(){
	var init = function(){onCreate();};
	var setContentView = function(){
		$('#header_brand').attr('src',app.img()+'/default/hanbit.jpg').css('height','80px').css('width','100px').css('padding-bottom','20px');
		$('#footer').addClass('bottom').addClass('footer');
		$('#global_content').addClass('box');
		$('#nav ul').addClass('list_style_none').addClass('over_hidden').addClass('bg_color_black')
		.css('margin','0').css('padding','0');
		$('#nav li').addClass('float_left').addClass('display_inline')
		.css('border-right','1px').css('solid','#bbb');
		$('#nav li:last-child').css('border-right','none');
		$('#nav li a').addClass('display_block').addClass('font_color_white').addClass('text_center').addClass('text_deco_none')
		.css('padding','14px 16px')
		$('#nav li a:hover:not(.active)').addClass('bg_color_green')
		$('#nav .active').addClass('bg_color_black');
	};
	var onCreate = function(){
		setContentView();
		$('#a_member').click(function(){controller.move('member','main');});
		$('#a_grade').click(function(){controller.move('grade','main');});
		$('#a_account').click(function(){controller.move('account','main');});
		$('#a_shool').click(function(){controller.move('global','school_info');});
	};
	return {
		init : init
	};
})(); 

var ACCOUNT =
'<link href="https://a2.muscache.com/airbnb/static/packages/common-86180c1646b448bc4a69535df81ff5de.css" media="all" rel="stylesheet" type="text/css">'
+'<div class="page-container-responsive space-top-4 space-4">'
+ '<div class="row">'
+ '<div class="col-md-3">'    
+ '<ul class="sidenav-list">'
+ '<li><a href="#" aria-selected="false" class="sidenav-item">Payment Methods</a></li>'
+ '<li><a href="#" aria-selected="false" class="sidenav-item">Transaction History</a></li>'
+ '<li><a href="#" aria-selected="false" class="sidenav-item">Change Password</a></li>'
+ '	<li>'
+ '<a href="#" aria-selected="false" class="sidenav-item">Remove Account</a>'
+ '</li>'
+ '</ul>'
+ '</div>'
+ '<div class="col-md-9">'
+ '<div class="panel">'
+ '<form accept-charset="UTF-8" action="https://www.airbnb.com/users/update_notifications/27430889" id="notification_settings_form" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓"><input name="authenticity_token" type="hidden" value="V4$.airbnb.com$Bs_UKVcOd84$zhU64aViGgU8vqLzRx_UJNSBJvszYBWE7HMICcIe0QQ="></div>'
+ '	<input id="id" name="id" type="hidden" value="27430889">'
+ '<div class="panel-header">'
+ 'Push Notification Settings'
+ '</div>'
+ '<section class="panel-body">'
+ 'div class="row">'
+ '<div class="col-sm-4">'
+ '<p>Receive Push Notifications to your iPhone, iPad or Android device.</p>'
+ '</div>'
+ '<div class="col-sm-8">'
+ '<div>'
+ 'Download the <a href="/mobile">Airbnb App</a> to receive push notifications instead of plain text messages. Once you enable push notifications on your mobile device, the settings will appear here.'
+ '</div>'
+ '</div>'
+ '</div>'
+ '</section>'
+ '</form></div>'
+ '<div class="panel space-top-4">'
+ '<div class="panel-header">'
+ 'Text Message Settings'
+ '</div>'
+ '<section class="panel-body">'
+ '<div class="row">'
+ '<div class="col-sm-4">'
+ '<p>Receive mobile updates by regular SMS text message.</p>'
+ '<p><b>Note:</b> For more information, text HELP to 247262. To cancel mobile notifications, reply STOP to 247262. Message and Data rates may apply.</p>'
+ '</div>'
+ '<div class="col-sm-8">'
+ '<div class="row">'
+ '<label class="col-sm-6" for="sms_phone_number_id">Receive SMS notifications to:'
+ '	<p><a href="${context}/member/edit">Change phone numbers</a></p>'
+ '</label>'
+ '<div class="select">'
+ '<select id="sms_phone_number_id" name="sms_phone_number_id"><option value="11625073" selected="selected">+1 *** *** 4345</option></select>'
+ '</div>'
+ '</div>'
+ '<label class="col-sm-1 checkbox">'
+ '<input checked="checked" id="sms_messages" name="sms[messages]" type="checkbox" value="1">'
+ '</label>'
+ '<label class="col-sm-11" for="settings_messages">'
+ '<strong>Messages</strong><br>'
+ 'From hosts and guests'
+ '</label>'
+ '<label class="col-sm-1 checkbox">'
+ '<input checked="checked" id="sms_reservations" name="sms[reservations]" type="checkbox" value="1">'
+ '</label>'
+ '<label class="col-sm-11" for="settings_messages">'
+ '<strong>Reservation Updates</strong><br>'
+ 'Requests, confirmations, changes and more'
+ '</label>'
+ '<label class="col-sm-1 checkbox">'
+ '<input checked="checked" id="sms_other" name="sms[other]" type="checkbox" value="1">'
+ '</label>'
+ '<label class="col-sm-11" for="settings_messages">'
+ '<strong>Other</strong><br>'
+ 'Feature updates and more'
+ '</label>'
+ '</div>'
+ '</div>'
+ '</section>'
+ '</div>'
+ '<div class="panel space-top-4">'
+ '<div class="panel-header">'
+ 'Email Settings'
+ '</div>'
+ '<section class="panel-body">'
+ '<div class="row">'
+ '<div class="col-sm-4">'
+ '<h5>I want to receive:</h5>'
+ '<p>You can disable these at any time.</p>'
+ '</div>'
+ '<div class="col-sm-8">'
+ '<label class="col-sm-1 checkbox">'
+ '<input name="user_profile_info[receive_promotional_email]" type="hidden" value="0"><input id="user_profile_info_receive_promotional_email" name="user_profile_info[receive_promotional_email]" type="checkbox" value="1">'
+ ' </label>'
+ ' <label class="col-sm-11" for="user_profile_info_receive_promotional_email">'
+ 'General promotions, updates, news about Airbnb or general promotions for partner campaigns and services, user surveys, inspiration, and love from Airbnb.'
+ ' </label>'
+ ' <label class="col-sm-1 checkbox">'
+ '   <input name="user_profile_info[receive_informative_email]" type="hidden" value="0"><input id="user_profile_info_receive_informative_email" name="user_profile_info[receive_informative_email]" type="checkbox" value="1">'
+ ' </label>'
+ ' <label class="col-sm-11" for="user_profile_info_receive_informative_email">'
+ '   Reservation and review reminders.'
+ ' </label>'
+ ' </div>'
+ '</div>'
+ '</section>'
+ '</div>'
+ ' <div class="panel space-top-4">'
+ '<div class="panel-header">'
+ 'Phone Preferences'
+ '</div>'
+ '<section class="panel-body">'
+ '<div class="row">'
+ '<div class="col-sm-4">'
+ '<h5>I want to receive:</h5>'
+ '<p>You can change this at any time.</p>'
+ '</div>'
+ '<div class="col-sm-8">'
+ '<label class="col-sm-1 checkbox">'
+ '<input checked="checked" id="can_receive_phone_call" name="can_receive_phone_call" type="checkbox" value="1">'
+ '</label>'
+ '<label class="col-sm-11" for="user_can_receive_phone_call">'
+ '<strong>Calls about my account, listings, reservations, or the Airbnb community</strong><br>'
+ 'If you opt out, we may still call you about your account if it’s urgent or if previous emails didn’t reach you.'
+ '</label>'
+ ' </div>'
+ '</div>'
+ '  </section>'
+ '</div>'
+ '<div class="panel-footer">'
+ '<input class="btn btn-primary" id="user_submit" name="commit" type="submit" value="Save">'
+ '</div>'
+ '</div>'
+ '</div>'
+'</div>';

var DASHBOARD = 
'<div class="page-container-responsive space-top-4 space-4">'
+'<div class="row">'
+'<div class="col-md-3">'
+'<div class="panel space-4">'
+'<div class="media media-photo-block">'
+'<a href="${context}/member/show/" title="View Profile"><img alt="Rachel" class="img-responsive" height="190" src="${img}/member/rachel.jpg" title="rachel" width="190" /></a>'
+'</div>'
+'<div class="panel-body">'
+'<h2 class="text-center">Rachel</h2>'
+'<ul class="list-unstyled text-center">'
+'<li><a href="${context}/member/show/">View Profile</a></li>'
+'<li><a href="${context}/member/edit/" id="edit-profile">Edit Profile</a>'
+'</li>'
+'</ul>'
+'</div>'
+'</div>'
+'<div class="panel space-4 verifications-panel-vertical ">'
+'<div class="panel-header row">'
+'<div class="pull-left">'
+'Verifications'
+'</div>'
+'<div class="pull-right">'
+'<i class="icon icon-question" id="tooltip-trigger"></i>'
+'<div class="tooltip tooltip-right-middle" role="tooltip" aria-hidden="true" data-trigger="#tooltip-trigger" data-sticky="true">'
+'<p class="panel-body">'
+'  Verifications help build trust between guests and hosts and can make booking easier.<a href="/help/article/336">Learn more »</a>'
+'</p>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="panel-body">'
+'<ul class="list-unstyled ">'
+'<li class="row row-condensed">'
+'<div class="media">'
+'  <i class="icon icon-ok icon-lima h3 pull-left"></i>'
+'  <div class="media-body">'
+'    <div>'
+'Email address'
+' </div>'
+' <div class="text-muted">'
+'Verified'
+'</div>'
+'  </div>'
+'</div>'
+'</li>'
+'<li class="row row-condensed">'
+'<div class="media">'
+'  <i class="icon icon-ok icon-lima h3 pull-left"></i>'
+'  <div class="media-body">'
+' <div>Phone number</div>'
+' <div class="text-muted">(▒▒▒) ▒▒▒-▒▒45</div>'
+'  </div>'
+'</div>'
+'</li>'
+'<li class="row row-condensed">'
+'<div class="media">'
+'  <i class="icon icon-ok icon-lima h3 pull-left"></i>'
+'  <div class="media-body">'
+' <div>'
+'   Reviewed'
+' </div>'
+' <div class="text-muted">'
+'   2 Reviews'
+' </div>'
+'  </div>'
+'</div>'
+'</li>'
+'<li class="row row-condensed">'
+'<div class="media">'
+'  <i class="icon icon-ok icon-lima h3 pull-left"></i>'
+'  <div class="media-body">'
+' <div>'
+' Personal info'
+' </div>'
+' <div class="text-muted">'
+'   Verified'
+' </div>'
+'  </div>'
+'</div>'
+'</li>'
+'</ul>'
+'	<a href="#">'
+'Add Verifications'
+'</a>'
+'</div>'
+'</div>'
+'<div class="panel space-4">'
+'<div class="panel-header">Quick Links</div>'
+'<div class="panel-body">'
+'  <ul class="list-unstyled">'
+' <li class="space-2">'
+'   <a href="${context}/member/trips">Upcoming Trips</a>'
+' </li>'
+' <li class="space-2">'
+'   <a href="#">Hosting on Airbnb</a>'
+' </li>'
+' <li class="space-2">'
+'   <a href="#">Traveling on Airbnb</a>'
+' </li>'
+' <li class="space-2">'
+'   <a href="#">Help Center</a>'
+' </li>'
+'  </ul>'
+'</div>'
+'</div>'
+'	</div>'
+'	<div class="col-md-9">'
+'<div class="panel space-4">'
+'<div class="panel-header">'
+'  Messages (1 new)'
+'</div>'
+'  <ul class="list-layout">'
+'<li class="panel-body thread-read thread" id="thread_172155785">'
+'<div class="row">'
+'<div class="col-3">'
+'<div class="row row-table">'
+'<div class="col-5">'
+'  <a href="#" target="_blank"><img alt="Ajit" class="img-round" height="50" src="https://a1.muscache.com/im/users/863155/profile_pic/1311564603/original.jpg?aki_policy=profile_small" title="Ajit" width="50" /></a>'
+'</div>'
+'<div class="col-7">'
+'  Ajit'
+'  <br/>'
+'  Feb 16'
+'</div>'
+'</div>'
+'</div>'
+'<a href="#" class="link-reset text-muted">'
+'<div class="col-7">'
+'	  Oknp. Sorry to hear about that. :( You were going t...<br/>'
+'<span class="text-muted">'
+' <span class=street-address>Norwalk Lane</span>, <span class=locality>Austin</span>, <span class=region>TX</span>'
+'   (Mar 9 - 16, 2016)'
+'</span>'
+'</div>'
+'</a>    <div class="col-2">'
+'<span class="label label-gray label-info">Canceled</span>'
+'<br/>'
+'$1588'
+'</div>'
+'	</div>'
+'</li>'
+'<li class="panel-body thread-read thread" id="thread_166764939">'
+'<div class="row">'
+'<div class="col-3">'
+'<div class="row row-table">'
+'<div class="col-5">'
+'<a href="#" target="_blank"><img alt="Richard" class="img-round" height="50" src="https://a0.muscache.com/im/users/15396185/profile_pic/1400523583/original.jpg?aki_policy=profile_small" title="Richard" width="50" /></a>'
+'</div>'
+'<div class="col-7">'
+'Richard'
+'  <br/>'
+'  Feb 09'
+'</div>'
+'</div>'
+'</div>'
+'<a href="#" class="link-reset text-muted">'
+'<div class="col-7">:)<br/>'
+'<span class="text-muted">'
+'<span class=street-address>Angell Street</span>, <span class=locality>Providence</span>, <span class=region>RI</span>'
+'(Feb 4 - 8, 2016)'
+'</span>'
+'</div>'
+'</a>    <div class="col-2">'
+'<span class="label label-green label-success">Accepted</span>'
+'<br/>'
+'$567'
+'</div>'
+'</div>'
+'</li>'
+'<li class="panel-body thread-read thread" id="thread_166762954">'
+'<div class="row">'
+'<div class="col-3">'
+'<div class="row row-table">'
+'<div class="col-5">'
+'<a href="#" target="_blank"><img alt="Elizabeth" class="img-round" height="50" src="https://a2.muscache.com/im/pictures/cb376bbf-677e-499a-8d2a-16e14c8e883c.jpg?aki_policy=profile_small" title="Elizabeth" width="50" /></a>'
+'</div>'
+'<div class="col-7">Elizabeth<br/>'
+'Jan 20'
+'</div>'
+'</div>'
+'</div>'
+'<a href="#" class="link-reset text-muted">'
+'<div class="col-7">'
+'Hi I&#x27;m a Brown alum visiting for recruiting events ...'
+'<br/>'
+'<span class="text-muted">'
+'<span class=street-address>Benefit Street</span>, <span class=locality>Providence</span>, <span class=region>RI</span>'
+'(Feb 4 - 8, 2016)'
+'</span>'
+'</div>'
+'</a>    <div class="col-2">'
+'<span class="label label-gray label-info">Canceled</span>'
+'<br/>'
+'$480'
+'</div>'
+'</div>'
+'</li>'
+'<li class="panel-body  thread" id="thread_97044264">'
+'<div class="row">'
+'<div class="col-3">'
+'<div class="row row-table">'
+'<div class="col-5">'
+'<a href="#" target="_blank"><img alt="Christiane" class="img-round" height="50" src="https://a2.muscache.com/im/users/2702141/profile_pic/1442827721/original.jpg?aki_policy=profile_small" title="Christiane" width="50" /></a>'
+'</div>'
+'<div class="col-7">'
+'Christian'
+'<br/>'
+'06/07/2015'
+'</div>'
+'</div>'
+'</div>'
+'<a href="#" class="link-reset ">'
+'<div class="col-7">'
+'<strong>'
+'Hi! I&#x27;m on the way and will be there in 15'
+'</strong>'
+'<br/>'
+'<span class="text-muted">'
+'<span class=street-address>West 15th Street</span>, <span class=locality>New York</span>, <span class=region>NY</span>'
+'(Jun 7 - 12, 2015)'
+'</span>'
+'</div>'
+'</a>    <div class="col-2">'
+'<span class="label label-green label-success">Accepted</span>'
+'<br/>'
+'$1724'
+'</div>'
+'</div>'
+'</li>'
+'<li class="panel-body thread-read thread" id="thread_97044261">'
+'<div class="row">'
+'<div class="col-3">'
+'<div class="row row-table">'
+'<div class="col-5">'
+'<a href="#" target="_blank"><img alt="Elnaz" class="img-round" height="50" src="https://a2.muscache.com/im/users/15447043/profile_pic/1401289639/original.jpg?aki_policy=profile_small" title="Elnaz" width="50" /></a>'
+'</div>'
+'<div class="col-7">'
+'  Elnaz'
+'  <br/>'
+'  05/07/2015'
+'</div>'
+'</div>'
+'</div>'
+'<a href="#" class="link-reset text-muted">'
+'<div class="col-7">Ok!<br/>'
+'<span class="text-muted">'
+'<span class=street-address>West 21st Street</span>, <span class=locality>New York</span>, <span class=region>NY</span>'
+'(Jun 8 - 12, 2015)'
+'</span>'
+'</div>'
+'</a><div class="col-2">'
+'<span class="label label-gray label-info">Canceled</span>'
+'<br/>'
+'$1750'
+'</div>'
+'</div>'
+'</li>'
+'  </ul>'
+'<div class="panel-body">'
+'<a href="${context}/member/inbox">All messages</a>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>';
