/**
 *2016/10/14 금 
 */

var booking = (function() {
	var init = function(){onCreate();};
	var setContentView = function() {};
	var onCreate = function() {
		setContentView();
		$('#pub_article').on('click','#submit_location',function(){
			$('#pub_article').html(BOOKING_FORM);
			$('#pub_article').on('click','#btn_filter',function(){
				$('#div_filter').hide();
				$('#result_list').hide();
				$('#div_size').show();
				$('#filter_location').show();
				$('#filter_submit').show();
			})
		});
		$('#pub_article').on('click','#detail_go',function(){
			$('#pub_article').html(DETAIL_FORM);
		});
		$('#pub_article').on('click','button[name=paying_go]',function(e){
			e.preventDefault();
			alert('hi2');
			$('#pub_article').html(PAYING_FORM);
		});
		$('#pub_article').on('click','#booking-item',function(){
			$('#pub_article').html(CANCEL_FORM);
		});
	}
	return{
		init : init
	}
})();

// 화면 FROM
var BOOKING_FORM = 
'<div class="map-search">'
+'<div class="sidebar" style="top: 10%; bottom: 10%;">'
+'<div id="katamari-container">'
+'<div>'
+'<div>'
+'<div>'
+'<div>'
+'<div class="filters collapse" style="">'
+'<div id="filter_options">'
+'<div class="panel-header filters-section show-sm">'
+'<span data-reactid=".qv0afapybk.0.0.0.0.0.0">검색필터</span>'
+'</div>'
+'<div class="filters-section panel-body panel-light intro-filter">'
+'<div class="row">'
+'<div class="col-lg-2 col-md-12 text-center-sm text-center-md space-sm-1 sectionLabel_rcr7sj">'
+'<div id="filter-section-header-dates">'
+'<span>날짜</span>'
+'</div>'
+'</div>'
+'<div class="col-lg-9 col-md-11">'
+'<div class="row row-condensed">'
+'<div>'
+'<div class="col-md-4 col-sm-6 space-1-sm">'
+'<label class="screen-reader-only" for="datespan-checkin">체크인</label>'
+'<input id="datespan-checkin" type="text" name="checkin" class="checkin ui-datepicker-target" value="2016/10/14" placeholder="체크인">'
+'</div>'
+'<div class="col-md-4 col-sm-6 space-1-sm">'
+'<label class="screen-reader-only" for="datespan-checkout">체크아웃</label>'
+'<input id="datespan-checkout" type="text" name="checkout" class="checkout ui-datepicker-target" value="2016/10/26" placeholder="체크아웃">'
+'</div>'
+'</div>'
+'<div class="col-md-4 col-sm-12 space-sm-1">'
+'<div class="select select-block">'
+'<label for="guest-select" class="screen-reader-only"><span>게스트 수</span></label>'
+'<select id="guest-select">'
+'<option selected="" value="1">숙박 인원 1명</option>'
+'<option value="2">숙박 인원 2명</option>'
+'<option value="3">숙박 인원 3명</option>'
+'<option value="4">숙박 인원 4명</option>'
+'<option value="5">숙박 인원 5명</option>'
+'<option value="6">숙박 인원 6명</option>'
+'<option value="7">숙박 인원 7명</option>'
+'<option value="8">숙박 인원 8명</option>'
+'<option value="9">숙박 인원 9명</option>'
+'<option value="10">숙박 인원 10명</option>'
+'<option value="11">숙박 인원 11명</option>'
+'<option value="12">숙박 인원 12명</option>'
+'<option value="13">숙박 인원 13명</option>'
+'<option value="14">숙박 인원 14명</option>'
+'<option value="15">숙박 인원 15명</option>'
+'<option value="16">숙박 인원 16+명</option>'
+'</select>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="filters-section panel-body panel-light intro-filter">'
+'<div class="row">'
+'<div class="col-lg-2 col-md-12 text-center-sm text-center-md space-sm-1 sectionLabel_rcr7sj">'
+'<div id="filter-section-header-room-types">'
+'<span>숙소 유형</span><span> </span><span><i class="icon icon-question hide-sm hide-md"></i><noscript></noscript></span>'
+'</div>'
+'</div>'
+'<div class="col-lg-9 col-md-11">'
+'<div class="row row-condensed" id="room-options">'
+'<div class="col-md-4 col-sm-12 space-sm-1">'
+'<label id="entire-place-checkbox-label" class="checkbox facet-checkbox facet-checkbox--room-type panel panel-dark" for="facet-checkbox-entire-place">'
+'<div class="facet-checkbox__icon-col"><i class="icon h5 icon-entire-place"></i>'
+'</div>'
+'<div class="facet-checkbox__label-col"><span>집 전체</span>'
+'</div>'
+'<div class="facet-checkbox__input-col">'
+'<input id="facet-checkbox-entire-place" type="checkbox" name="room-type" aria-labelledby="filter-section-header-room-types entire-place-checkbox-label" aria-describedby="entire-place-desc" value="집 전체">'
+'</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4 col-sm-12 space-sm-1">'
+'<label id="private-room-checkbox-label" class="checkbox facet-checkbox facet-checkbox--room-type panel panel-dark" for="facet-checkbox-private-room">'
+'<div class="facet-checkbox__icon-col"><i class="icon h5 icon-private-room"></i>'
+'</div>'
+'<div class="facet-checkbox__label-col"><span>개인실</span>'
+'</div>'
+'<div class="facet-checkbox__input-col">'
+'<input id="facet-checkbox-private-room" type="checkbox" name="room-type" aria-labelledby="filter-section-header-room-types private-room-checkbox-label" aria-describedby="private-room-desc" value="개인실">'
+'</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4 col-sm-12 space-sm-1">'
+'<label id="shared-room-checkbox-label" class="checkbox facet-checkbox facet-checkbox--room-type panel panel-dark" for="facet-checkbox-shared-room">'
+'<div class="facet-checkbox__icon-col"><i class="icon h5 icon-shared-room"></i>'
+'</div>'
+'<div class="facet-checkbox__label-col">'
+'<span>다인실</span>'
+'</div>'
+'<div class="facet-checkbox__input-col">'
+'<input id="facet-checkbox-shared-room" type="checkbox" name="room-type" aria-labelledby="filter-section-header-room-types shared-room-checkbox-label" aria-describedby="shared-room-desc" value="다인실">'
+'</div>'
+'</label>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="filters-section panel-body panel-light intro-filter">'
+'<div class="row">'
+'<div class="col-lg-2 col-md-12 text-center-sm text-center-md space-sm-1 sectionLabel_rcr7sj">'
+'<div id="filter-section-header-price">'
+'<span>가격 범위</span>'
+'</div>'
+'</div>'
+'<div class="col-lg-9 col-md-11"><div class="col-md-4 col-sm-6 space-1-sm" style="display : inline;"><input type="text" placeholder="부터" style="text-align:right;" /></div><div class="col-md-4 col-sm-6 space-1-sm" style="display : inline;"><input type="text" placeholder="까지" style="text-align:right;" /></div>'
+'<div>'
+'</div>'	
+'</div>'
+'<div class="dynamic-filters filters-section">'
+'<div class="filters-section panel-body panel-light">'
+'<div class="row">'
+'<div class="col-lg-2 col-md-12 text-center-sm text-center-md space-sm-1 sectionLabel_rcr7sj">'
+'<div id="filter-section-header-amenities">'
+'<span>시설</span>'
+'</div>'
+'</div>'
+'<div class="col-lg-9 col-md-11">'
+'<div>'
+'<div class="row row-condensed">'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="무선 인터넷" for="filter-option-amenities-4">'
+'<div>'
+'<input id="filter-option-amenities-4" type="checkbox" value="무선 인터넷">'
+'</div>'
+'<div>무선 인터넷</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="수영장" for="filter-option-amenities-7">'
+'<div>'
+'<input id="filter-option-amenities-7" type="checkbox" value="수영장">'
+'</div>'
+'<div>수영장</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="부엌" for="filter-option-amenities-8">'
+'<div>'
+'<input id="filter-option-amenities-8" type="checkbox" value="부엌">'
+'</div>'
+'<div>부엌</div>'
+'</label>'
+'</div>'
+'</div>'
+'<div class="filters-more collapse"><hr><div class="row row-condensed">'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="24시간 체크인" for="filter-option-amenities-43">'
+'<div>'
+'<input id="filter-option-amenities-43" type="checkbox" value="24시간 체크인">'
+'</div>'
+'<div>24시간 체크인</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="TV" for="filter-option-amenities-1">'
+'<div>'
+'<input id="filter-option-amenities-1" type="checkbox" value="TV">'
+'</div>'
+'<div>TV</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="가족/어린이 환영" for="filter-option-amenities-31">'
+'<div>'
+'<input id="filter-option-amenities-31" type="checkbox" value="가족/어린이 환영">'
+'</div>'
+'<div>가족/어린이 환영</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="건물 내 엘리베이터" for="filter-option-amenities-21">'
+'<div>'
+'<input id="filter-option-amenities-21" type="checkbox" value="건물 내 엘리베이터">'
+'</div>'
+'<div>건물 내 엘리베이터</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="건조기" for="filter-option-amenities-34">'
+'<div>'
+'<input id="filter-option-amenities-34" type="checkbox" value="건조기">'
+'</div>'
+'<div>건조기</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="구급 상자" for="filter-option-amenities-37">'
+'<div>'
+'<input id="filter-option-amenities-37" type="checkbox" value="구급 상자">'
+'</div>'
+'<div>구급 상자</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="난방" for="filter-option-amenities-30">'
+'<div>'
+'<input id="filter-option-amenities-30" type="checkbox" value="난방">'
+'</div>'
+'<div>난방</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="노트북 작업 공간" for="filter-option-amenities-47">'
+'<div>'
+'<input id="filter-option-amenities-47" type="checkbox" value="노트북 작업 공간">'
+'</div>'
+'<div>노트북 작업 공간</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="다리미" for="filter-option-amenities-46">'
+'<div>'
+'<input id="filter-option-amenities-46" type="checkbox" value="다리미">'
+'</div>'
+'<div>다리미</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="도어맨" for="filter-option-amenities-14">'
+'<div>'
+'<input id="filter-option-amenities-14" type="checkbox" value="도어맨">'
+'</div>'
+'<div>도어맨</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="무료 헬스장" for="filter-option-amenities-15">'
+'<div>'
+'<input id="filter-option-amenities-15" type="checkbox" value="무료 헬스장">'
+'</div>'
+'<div>무료 헬스장</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="무료주차 포함" for="filter-option-amenities-9">'
+'<div>'
+'<input id="filter-option-amenities-9" type="checkbox" value="무료주차 포함">'
+'</div>'
+'<div>무료주차 포함</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="반려동물 입실 가능" for="filter-option-amenities-12">'
+'<div>'
+'<input id="filter-option-amenities-12" type="checkbox" value="반려동물 입실 가능">'
+'</div>'
+'<div>반려동물 입실 가능</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="샴푸" for="filter-option-amenities-41">'
+'<div>'
+'<input id="filter-option-amenities-41" type="checkbox" value="샴푸">'
+'</div>'
+'<div>샴푸</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="세탁기" for="filter-option-amenities-33">'
+'<div>'
+'<input id="filter-option-amenities-33" type="checkbox" value="세탁기">'
+'</div>'
+'<div>세탁기</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="소화기" for="filter-option-amenities-39">'
+'<div>'
+'<input id="filter-option-amenities-39" type="checkbox" value="소화기">'
+'</div>'
+'<div>소화기</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="실내 벽난로" for="filter-option-amenities-27">'
+'<div>'
+'<input id="filter-option-amenities-27" type="checkbox" value="실내 벽난로">'
+'</div>'
+'<div>실내 벽난로</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="아침식사" for="filter-option-amenities-16">'
+'<div>'
+'<input id="filter-option-amenities-16" type="checkbox" value="아침식사">'
+'</div>'
+'<div>아침식사</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="안전 카드" for="filter-option-amenities-38">'
+'<div>'
+'<input id="filter-option-amenities-38" type="checkbox" value="안전 카드">'
+'</div>'
+'<div>안전 카드</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="에어컨" for="filter-option-amenities-5">'
+'<div>'
+'<input id="filter-option-amenities-5" type="checkbox" value="에어컨">'
+'</div>'
+'<div>에어컨</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="옷걸이" for="filter-option-amenities-44">'
+'<div>'
+'<input id="filter-option-amenities-44" type="checkbox" value="옷걸이">'
+'</div>'
+'<div>옷걸이</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="이벤트/행사 가능" for="filter-option-amenities-32">'
+'<div>'
+'<input id="filter-option-amenities-32" type="checkbox" value="이벤트/행사 가능">'
+'</div>'
+'<div>이벤트/행사 가능</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="인터넷" for="filter-option-amenities-3">'
+'<div>'
+'<input id="filter-option-amenities-3" type="checkbox" value="인터넷">'
+'</div>'
+'<div>인터넷</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="일산화탄소 감지기" for="filter-option-amenities-36">'
+'<div>'
+'<input id="filter-option-amenities-36" type="checkbox" value="일산화탄소 감지기">'
+'</div>'
+'<div>일산화탄소 감지기</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="자쿠지 욕조" for="filter-option-amenities-25">'
+'<div>'
+'<input id="filter-option-amenities-25" type="checkbox" value="자쿠지 욕조">'
+'</div>'
+'<div>자쿠지 욕조</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="초인종/인터폰" for="filter-option-amenities-28">'
+'<div>'
+'<input id="filter-option-amenities-28" type="checkbox" value="초인종/인터폰">'
+'</div>'
+'<div>초인종/인터폰</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="침실문 잠금장치" for="filter-option-amenities-42">'
+'<div>'
+'<input id="filter-option-amenities-42" type="checkbox" value="침실문 잠금장치">'
+'</div>'
+'<div>침실문 잠금장치</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="케이블 TV" for="filter-option-amenities-2">'
+'<div>'
+'<input id="filter-option-amenities-2" type="checkbox" value="케이블 TV">'
+'</div>'
+'<div>케이블 TV</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="필수품목" for="filter-option-amenities-40">'
+'<div>'
+'<input id="filter-option-amenities-40" type="checkbox" value="필수품목">'
+'</div>'
+'<div>필수품목</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="헤어 드라이기" for="filter-option-amenities-45">'
+'<div>'
+'<input id="filter-option-amenities-45" type="checkbox" value="헤어 드라이기">'
+'</div>'
+'<div>헤어 드라이기</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="화재 감지기" for="filter-option-amenities-35">'
+'<div>'
+'<input id="filter-option-amenities-35" type="checkbox" value="화재 감지기">'
+'</div>'
+'<div>화재 감지기</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="휠체어 사용 가능" for="filter-option-amenities-6">'
+'<div>'
+'<input id="filter-option-amenities-6" type="checkbox" value="휠체어 사용 가능">'
+'</div>'
+'<div>휠체어 사용 가능</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="흡연 가능" for="filter-option-amenities-11">'
+'<div>'
+'<input id="filter-option-amenities-11" type="checkbox" value="흡연 가능">'
+'</div>'
+'<div>흡연 가능</div>'
+'</label>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="col-md-1">'
+'<button class="btn-link btn-link--icon sectionLabel_rcr7sj"><i class="icon icon-caret-down hide-sm"></i>'
+'<strong class="text-muted show-sm">'
+'<span>+ 더보기</span>'
+'</strong>'
+'</button>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="panel-body panel-light show-sm">'
+'<div class="sticky-apply-filters-placeholder">'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div id="div_size" class="filters-section panel-body panel-light">'
+'<div class="row">'
+'<div class="col-lg-2 col-md-12 text-center-sm text-center-md space-sm-1 sectionLabel_rcr7sj">'
+'<div id="filter-section-header-size">'
+'<span>규모</span>'
+'</div>'
+'</div>'
+'<div class="col-lg-9 col-md-11">'
+'<div class="row row-condensed">'
+'<div class="col-md-4 col-sm-12 space-sm-1">'
+'<div class="select select-block">'
+'<label for="map-search-min_bedrooms" class="screen-reader-only">'
+'<span>침실 최소 개수</span>'
+'</label>'
+'<select id="map-search-min_bedrooms">'
+'<option selected="" value="-1">침실 수</option>'
+'<option value="1">침실 1개</option>'
+'<option value="2">침실 2개</option>'
+'<option value="3">침실 3개</option>'
+'<option value="4">침실 4개</option>'
+'<option value="5">침실 5개</option>'
+'<option value="6">침실 6개</option>'
+'<option value="7">침실 7개</option>'
+'<option value="8">침실 8개</option>'
+'<option value="9">침실 9개</option>'
+'<option value="10">침실 10개</option>'
+'</select>'
+'</div>'
+'</div>'
+'<div class="col-md-4 col-sm-12 space-sm-1">'
+'<div class="select select-block">'
+'<label for="map-search-min_bathrooms" class="screen-reader-only">'
+'<span>욕실 최소 개수</span>'
+'</label>'
+'<select id="map-search-min_bathrooms">'
+'<option selected="" value="-1">욕실 수</option>'
+'<option value="0">욕실 0개</option>'
+'<option value="0.5">욕실 0.5개</option>'
+'<option value="1">욕실 1개</option>'
+'<option value="1.5">욕실 1.5개</option>'
+'<option value="2">욕실 2개</option>'
+'<option value="2.5">욕실 2.5개</option>'
+'<option value="3">욕실 3개</option>'
+'<option value="3.5">욕실 3.5개</option>'
+'<option value="4">욕실 4개</option>'
+'<option value="4.5">욕실 4.5개</option>'
+'<option value="5">욕실 5개</option>'
+'<option value="5.5">욕실 5.5개</option>'
+'<option value="6">욕실 6개</option>'
+'<option value="6.5">욕실 6.5개</option>'
+'<option value="7">욕실 7개</option>'
+'<option value="7.5">욕실 7.5개</option>'
+'<option value="8">욕실 8+개</option>'
+'</select>'
+'</div>'
+'</div>'
+'<div class="col-md-4 col-sm-12 space-sm-1">'
+'<div class="select select-block">'
+'<label for="map-search-min_beds" class="screen-reader-only">'
+'<span>침대 최소 개수</span>'
+'</label>'
+'<select id="map-search-min_beds">'
+'<option selected="" value="-1">침대 수</option>'
+'<option value="1">침대 1개</option>'
+'<option value="2">침대 2개</option>'
+'<option value="3">침대 3개</option>'
+'<option value="4">침대 4개</option>'
+'<option value="5">침대 5개</option>'
+'<option value="6">침대 6개</option>'
+'<option value="7">침대 7개</option>'
+'<option value="8">침대 8개</option>'
+'<option value="9">침대 9개</option>'
+'<option value="10">침대 10개</option>'
+'<option value="11">침대 11개</option>'
+'<option value="12">침대 12개</option>'
+'<option value="13">침대 13개</option>'
+'<option value="14">침대 14개</option>'
+'<option value="15">침대 15개</option>'
+'<option value="16">침대 16+개</option>'
+'</select>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div id="filter_location" class="filters-section panel-body panel-light">'
+'<div class="row">'
+'<div class="col-lg-2 col-md-12 text-center-sm text-center-md space-sm-1 sectionLabel_rcr7sj">'
+'<div id="filter-section-header-neighborhoods">'
+'<span>지역</span>'
+'</div>'
+'</div>'
+'<div class="col-lg-9 col-md-11">'
+'<div>'
+'<div class="row row-condensed">'
+'<div class="col-md-4">'
+'<div>'
+'<input type="checkbox" value="신주쿠(Shinjuku)">신주쿠(Shinjuku)'
+'</div>'
+'<div></div>'
+'</div>'
+'</div>'
+ '<div class="filters-more collapse"><hr>'
+'<div class="row row-condensed">'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="나카노 지역" for="filter-option-neighborhoods-Nakano District">'
+'<div>'
+'<input id="filter-option-neighborhoods-Nakano District" type="checkbox" value="나카노 지역">'
+'</div>'
+'<div>나카노 지역</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="나카메구로(Nakameguro)" for="filter-option-neighborhoods-Nakameguro">'
+'<div>'
+'<input id="filter-option-neighborhoods-Nakameguro" type="checkbox" value="나카메구로(Nakameguro)">'
+'</div>'
+'<div>나카메구로(Nakameguro)</div>'
+'</label>'
+'</div>'
+'<div class="col-md-4">'
+'<label class="media checkbox facet-checkbox" title="네리마 지역" for="filter-option-neighborhoods-Nerima District">'
+'<div>'
+'<input id="filter-option-neighborhoods-Nerima District" type="checkbox" value="네리마 지역">'
+'</div>'
+'<div>네리마 지역</div>'
+'</label>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="col-md-1">'
+'</div>'
+'</div>'
+'</div>'
+'<div id="filter_submit" class="panel-light panel-btn-sm filters-footer-sm fixed">'
+'<div class="row row-condensed">'
+'<div class="col-md-8 col-lg-7 col-md-offset-4 col-lg-offset-5">'
+'<div class="row row-condensed space-sm-7">'
+'<div class="col-sm-6">'
+'<button class="btn btn-block cancel-btn">'
+'<span>취소</span>'
+'</button>'
+'</div>'
+'<div class="col-sm-6">'
+'<button class="btn btn-block btn-primary apply-filters-btn" disabled="">'
+'<span>필터 적용하기</span>'
+'</button>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div id="div_filter" class="sidebar-header panel-body clearfix panel-light">'
+'<div class="pull-left">'
+'<div>'
+'<div class="applied-filters-container hide-sm">'
+'<span class="pull-left show-filters">'
+'<button type="button" class="btn" id="btn_filter">'
+'<span>검색필터</span>'
+'<span> </span>'
+'</button>'
+'</span><ul class="applied-filters list-unstyled"></ul>'
+'</div>'
+'</div>'
+'</div>'
+'<div>'
+'<div class="crossfading-panel__container text-right pull-right show-lg">'
+'<div class="crossfading-panel crossfading-panel__vertically-centered-container crossfading-panel--right crossfading-panel--invisible"><h1 class="crossfading-panel--vertically-centered h6 text-right pull-right">'
+'<span>예약 가능 숙소 146 개</span>'
+'<span><span> · </span><span>도쿄</span></span></h1>'
+'</div>'
+'<div class="crossfading-panel crossfading-panel--right pull-right urgency-commitment-panel"><i class="icon pull-right urgency-commitment-panel--icon icon-calendar-trend crossfading-panel--margin-left"></i>'
+'<div class="pull-right crossfading-panel__text--lg">'
+'<strong>이 날짜에는 숙소가 2%만 남아있습니다.</strong>'
+'<div>'
+'<div class="crossfading-panel-body-text text-muted">'
+'<div class="ucBody_1elyhsq">곧 예약하시는 걸 권해드립니다.</div>'
+'<div class="learnMoreLink_jcsji7"></div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="crossfading-panel__container text-left pull-left crossfading-panel__container--md show-md">'
+'<div class="crossfading-panel crossfading-panel__vertically-centered-container crossfading-panel--invisible"><h1 class="crossfading-panel--vertically-centered h6 text-left crossfading-panel--margin-left">'
+'<span>예약 가능 숙소 146 개</span>'
+'<span><span> · </span>'
+'<span>도쿄</span>'
+'</span></h1>'
+'</div>'
+'<div class="crossfading-panel crossfading-panel--left pull-left urgency-commitment-panel"><i class="icon pull-left urgency-commitment-panel--icon icon-calendar-trend crossfading-panel--margin-right hide-sm"></i>'
+'<div class="pull-left text-center-sm crossfading-panel__text--md">'
+'<strong>이 날짜에는 숙소가 2%만 남아있습니다.</strong>'
+'<div>'
+'<div class="crossfading-panel-body-text text-muted">'
+'<div class="ucBody_1elyhsq">곧 예약하시는 걸 권해드립니다.</div>'
+'<div class="learnMoreLink_jcsji7"></div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="hide-filters-open-sm">'
+'<div class="space-sm-1 space-top-sm-1">'
+'<div class="disclaimer-wrapper">'
+'<div class="pricing-disclaimer text-muted"><i class="icon icon-currency-krw"></i>'
+'<span>추가 수수료가 부과됩니다. 세금도 부과될 수 있습니다.</span>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="sidebar-header-placeholder"></div>'
+'<div id="result_list" aria-live="polite" class="search-results">'
+'<div></div>'
+'<div></div>'
+'<div class="outer-listings-container space-2">'
+'<div class="listings-container">'
+'<div class="row">'
+'<div class="listing-card-wrapper col-sm-12 space-2 col-md-6">'
+'<div class="listing" itemscope="" itemtype="http://schema.org/Enumeration">'
+'<div class="panel-image listing-img">'
+'<div><a id="detail_go" href="#" class="media-photo media-cover">'
+'<div class="listing-img-container media-cover text-center">'
+'<img src="https://a1.muscache.com/im/pictures/ec045e43-bec3-4661-9b98-6ff834a9bb6e.jpg?aki_policy=x_medium" class="img-responsive-height" alt="2LDK(88㎡)Shinjuku 6min train!PrivateHouse!FreeWifi - 단독주택">'
+'</div></a>'
+'<a href="/rooms/15347688?checkin=2016%2F10%2F14&amp;checkout=2016%2F10%2F26&amp;guests=1" target="listing_15347688">'
+'<div class="panel-overlay-bottom-left panel-overlay-label panel-overlay-listing-label">'
+'<div class="price-label">'
+'<span><sup class="currency-prefix">₩</sup><span class="price-amount">193341</span>'
+'<span> </span>'
+'</span>'
+'<span><span> </span>'
+'<span>'
+'<span> </span>'
+'<span class="instant-book-trigger-wrapper">'
+'<span><i class="icon icon-instant-book icon-flush-sides icon-beach"></i></span>'
+'</span>'
+'</span>'
+'</span>'
+'</div>'
+'</div></a>'
+'<div class="panel-overlay-top-right wl-social-connection-panel">'
+'<span class="rich-toggle wish_list_button wishlist-button not_saved" role="button" style="display:block;width:32px;height:32px;"></span>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="panel-body panel-card-section">'
+'<div class="media"><h3 title="2LDK(88㎡)Shinjuku 6min train!PrivateHouse!FreeWifi" class="h5 listing-name text-truncate space-top-1"><span></span><span> </span></span><a href="#" class="text-normal"><span class="listing-name--display">2LDK(88㎡)Shinjuku 6min train!PrivateHouse!FreeWifi</span></a></h3><a href="#" class="text-normal link-reset">'
+'<div class="text-muted listing-location text-truncate">'
+'<div><span>집 전체</span><span class="person-capacity hide-md"><span> · </span><span>숙박 인원 11명</span></span></div>'
+'</div></a>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="listing-card-wrapper col-sm-12 space-2 col-md-6">'
+'<div class="listing" itemscope="" itemtype="http://schema.org/Enumeration">'
+'<div class="panel-image listing-img">'
+'<div><a href="/rooms/15347688?checkin=2016%2F10%2F14&amp;checkout=2016%2F10%2F26&amp;guests=1" class="media-photo media-cover" target="listing_15347688">'
+'<div class="listing-img-container media-cover text-center">'
+'<img src="https://a1.muscache.com/im/pictures/ec045e43-bec3-4661-9b98-6ff834a9bb6e.jpg?aki_policy=x_medium" class="img-responsive-height" alt="2LDK(88㎡)Shinjuku 6min train!PrivateHouse!FreeWifi - 단독주택">'
+'</div></a>'
+'<a href="/rooms/15347688?checkin=2016%2F10%2F14&amp;checkout=2016%2F10%2F26&amp;guests=1" target="listing_15347688">'
+'<div class="panel-overlay-bottom-left panel-overlay-label panel-overlay-listing-label">'
+'<div class="price-label">'
+'<span><sup class="currency-prefix">₩</sup><span class="price-amount">193341</span>'
+'<span> </span>'
+'</span>'
+'<span><span> </span>'
+'<span>'
+'<span> </span>'
+'<span class="instant-book-trigger-wrapper">'
+'<span><i class="icon icon-instant-book icon-flush-sides icon-beach"></i></span>'
+'</span>'
+'</span>'
+'</span>'
+'</div>'
+'</div></a>'
+'<div class="panel-overlay-top-right wl-social-connection-panel">'
+'<span class="rich-toggle wish_list_button wishlist-button not_saved" role="button" style="display:block;width:32px;height:32px;"></span>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="panel-body panel-card-section">'
+'<div class="media"><h3 title="2LDK(88㎡)Shinjuku 6min train!PrivateHouse!FreeWifi" class="h5 listing-name text-truncate space-top-1"><span></span><span> </span></span><a href="#" class="text-normal"><span class="listing-name--display">2LDK(88㎡)Shinjuku 6min train!PrivateHouse!FreeWifi</span></a></h3><a href="#" class="text-normal link-reset">'
+'<div class="text-muted listing-location text-truncate">'
+'<div><span>집 전체</span><span class="person-capacity hide-md"><span> · </span><span>숙박 인원 11명</span></span></div>'
+'</div></a>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+''
+'<div class="row">'
+'<div class="listing-card-wrapper col-sm-12 space-2 col-md-6">'
+'<div class="listing" itemscope="" itemtype="http://schema.org/Enumeration">'
+'<div class="panel-image listing-img">'
+'<div><a href="/rooms/15347688?checkin=2016%2F10%2F14&amp;checkout=2016%2F10%2F26&amp;guests=1" class="media-photo media-cover" target="listing_15347688">'
+'<div class="listing-img-container media-cover text-center">'
+'<img src="https://a1.muscache.com/im/pictures/ec045e43-bec3-4661-9b98-6ff834a9bb6e.jpg?aki_policy=x_medium" class="img-responsive-height" alt="2LDK(88㎡)Shinjuku 6min train!PrivateHouse!FreeWifi - 단독주택">'
+'</div></a>'
+'<a href="/rooms/15347688?checkin=2016%2F10%2F14&amp;checkout=2016%2F10%2F26&amp;guests=1" target="listing_15347688">'
+'<div class="panel-overlay-bottom-left panel-overlay-label panel-overlay-listing-label">'
+'<div class="price-label">'
+'<span><sup class="currency-prefix">₩</sup><span class="price-amount">193341</span>'
+'<span> </span>'
+'</span>'
+'<span><span> </span>'
+'<span>'
+'<span> </span>'
+'<span class="instant-book-trigger-wrapper">'
+'<span><i class="icon icon-instant-book icon-flush-sides icon-beach"></i></span>'
+'</span>'
+'</span>'
+'</span>'
+'</div>'
+'</div></a>'
+'<div class="panel-overlay-top-right wl-social-connection-panel">'
+'<span class="rich-toggle wish_list_button wishlist-button not_saved" role="button" style="display:block;width:32px;height:32px;"></span>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="panel-body panel-card-section">'
+'<div class="media"><h3 title="2LDK(88㎡)Shinjuku 6min train!PrivateHouse!FreeWifi" class="h5 listing-name text-truncate space-top-1"><span></span><span> </span></span><a href="#" class="text-normal"><span class="listing-name--display">2LDK(88㎡)Shinjuku 6min train!PrivateHouse!FreeWifi</span></a></h3><a href="#" class="text-normal link-reset">'
+'<div class="text-muted listing-location text-truncate">'
+'<div><span>집 전체</span><span class="person-capacity hide-md"><span> · </span><span>숙박 인원 11명</span></span></div>'
+'</div></a>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="listing-card-wrapper col-sm-12 space-2 col-md-6">'
+'<div class="listing" itemscope="" itemtype="http://schema.org/Enumeration">'
+'<div class="panel-image listing-img">'
+'<div><a href="/rooms/15347688?checkin=2016%2F10%2F14&amp;checkout=2016%2F10%2F26&amp;guests=1" class="media-photo media-cover" target="listing_15347688">'
+'<div class="listing-img-container media-cover text-center">'
+'<img src="https://a1.muscache.com/im/pictures/ec045e43-bec3-4661-9b98-6ff834a9bb6e.jpg?aki_policy=x_medium" class="img-responsive-height" alt="2LDK(88㎡)Shinjuku 6min train!PrivateHouse!FreeWifi - 단독주택">'
+'</div></a>'
+'<a href="/rooms/15347688?checkin=2016%2F10%2F14&amp;checkout=2016%2F10%2F26&amp;guests=1" target="listing_15347688">'
+'<div class="panel-overlay-bottom-left panel-overlay-label panel-overlay-listing-label">'
+'<div class="price-label">'
+'<span><sup class="currency-prefix">₩</sup><span class="price-amount">193341</span>'
+'<span> </span>'
+'</span>'
+'<span><span> </span>'
+'<span>'
+'<span> </span>'
+'<span class="instant-book-trigger-wrapper">'
+'<span><i class="icon icon-instant-book icon-flush-sides icon-beach"></i></span>'
+'</span>'
+'</span>'
+'</span>'
+'</div>'
+'</div></a>'
+'<div class="panel-overlay-top-right wl-social-connection-panel">'
+'<span class="rich-toggle wish_list_button wishlist-button not_saved" role="button" style="display:block;width:32px;height:32px;"></span>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="panel-body panel-card-section">'
+'<div class="media"><h3 title="2LDK(88㎡)Shinjuku 6min train!PrivateHouse!FreeWifi" class="h5 listing-name text-truncate space-top-1"><span></span><span> </span></span><a href="#" class="text-normal"><span class="listing-name--display">2LDK(88㎡)Shinjuku 6min train!PrivateHouse!FreeWifi</span></a></h3><a href="#" class="text-normal link-reset">'
+'<div class="text-muted listing-location text-truncate">'
+'<div><span>집 전체</span><span class="person-capacity hide-md"><span> · </span><span>숙박 인원 11명</span></span></div>'
+'</div></a>'
+'</div>'
+'</div>'
+'</div>'
+''
+'</div>'
+'</div>'
+'<span style="font-size:0;"></span>'
+'</div>'
+'</div>'
+'<div class="results-footer">'
+'<div class="pagination-buttons-container space-8">'
+'<div class="results_count">'
+'<span><span><span>예약 가능 숙소 146 개</span></span><span> 중 </span><span>1</span><span> – </span><span>18</span></span>'
+'</div>'
+'<div class="pagination pagination-responsive">'
+'</div>'
+'</div>'
+'</div>'
+'<div class="container_e6l7gr">'
+'<button aria-disabled="false" type="button" class="container_nih30w-o_O-container_180u7sb">'
+'<span class="text_1f104np-o_O-text_v1ofku">'
+'<span>검색필터</span>'
+'</span>'
+'</button>'
+'</div>'
+'</div>'
+'<div></div>'
+'<div></div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+''
+'<div class="map hide-sm" style="top: 10%; bottom: 10%;">'
+'맵임'
+'</div>'
+''
+'</div>';
var DETAIL_FORM = '<div id="room">'
+'<div id="photos" class="with-photos with-modal"><img alt="img" src="/web/resources/img/default.jpg" width="100%" height="550px" style="padding-bottom : 5%;"/>'
+'</div>'
+'<div id="summary" class="panel room-section">'
+'<div class="page-container-responsive">'
+'<div class="row">'
+'<div class="col-lg-8">'
+'<div>'
+'<div class="summary-component">'
+'<div class="space-4 space-top-4">'
+'<div class="row">'
+'<div class="col-md-3 space-sm-4 text-center space-sm-2">'
+'<div class="media-photo-badge"><a class="media-photo media-round"><img alt="사용자 프로필 이미지" class="host-profile-image" height="115" width="115" data-pin-nopin="true" src="/web/resources/img/default.jpg" title="Donald"></a>'
+'</div>'
+'</div>'
+'<div class="col-md-9">'
+'<h1 class="overflow h3 space-1 text-center-sm" id="listing_name">Ocean Front Condo by Owner</h1>'
+'<div id="display-address" class="space-2 text-muted text-center-sm"><a href="#neighborhood" class="link-reset">노스 머틀 비치, 사우스캐롤라이나, 미국</a>'
+'<span> &nbsp; </span>'
+'</div>'
+'<div class="row row-condensed text-muted text-center">'
+'<div class="col-sm-3">'
+'<i class="icon icon-entire-place icon-size-2" aria-hidden="true"></i>'
+'</div>'
+'<div class="col-sm-3">'
+'<i class="icon icon-group icon-size-2" aria-hidden="true"></i>'
+'</div>'
+'<div class="col-sm-3">'
+'<i class="icon icon-rooms icon-size-2" aria-hidden="true"></i>'
+'</div>'
+'<div class="col-sm-3">'
+'<i class="icon icon-double-bed icon-size-2" aria-hidden="true"></i>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="row">'
+'<div class="col-md-3 text-muted text-center hide-sm">'
+'<a href="#host-profile" class="link-reset text-wrap">Donald</a>'
+'</div>'
+'<div class="col-md-9">'
+'<div class="row row-condensed text-muted text-center">'
+'<div class="col-sm-3">집 전체</div>'
+'<div class="col-sm-3">숙박 인원 3명</div>'
+'<div class="col-sm-3">침실 1개</div>'
+'<div class="col-sm-3">침대 1개</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
 +'<div class="col-lg-4">'
 +'<div class="mobile-bookit-btn-container js-bookit-btn-container panel-btn-sm panel-btn-fixed-sm hide hide-md hide-lg">'
+'<button name="paying_go" class="btn btn-primary btn-block btn-large js-book-it-sm-trigger">'
+'<span class="book-it__btn-text">예약 요청</span>'
 +'<span class="book-it__btn-text--contact-host">호스트에게 연락하기</span>'
+'<span class="book-it__btn-text--instant"><i class="icon icon-bolt icon-beach h4"></i>즉시 예약 </span>'
 +'</button>'
+'</div>'
+''
+'<div id="tax-descriptions-tip" class="tooltip tooltip-top-middle" role="tooltip" data-sticky="true" data-trigger="#tax-descriptions-tooltip">'
+'</div>'
+''
+''
 +'<div>'
+'<div class="book-it__container js-book-it-container fixed" style="top: 40px;">'
+'<div>'
+'<div>'
+'<div class="">'
+'<div class="book-it__price fixed" style="height: 40px;">'
+'<div class="row">'
+'<div class="col-sm-8">'
+'<div class="book-it__price-amount text-special">'
+'<span class="h3"><span>₩74315</span></span>'
+'</div>'
+'</div>'
+'<div class="col-sm-4">'
+'<div class="book-it__payment-period-container pull-right">'
+'<div class="book-it__payment-period"><span>1박</span>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<form method="post">'
+'<div class="panel book-it-panel">'
+'<div class="panel-body panel-light">'
+'<div class="row row-condensed space-3">'
+'<div class="col-md-9">'
+'<div class="row row-condensed">'
+'<div class="col-sm-6">'
+'<label class="book-it__label" for="datespan-checkin">체크인</label>'
+'<input id="datespan-checkin" type="text" name="checkin" class="checkin ui-datepicker-target" placeholder="년/월/일">'
+'</div>'
+'<div class="col-sm-6">'
+'<label class="book-it__label" for="datespan-checkout">체크아웃</label>'
+'<input id="datespan-checkout" type="text" name="checkout" class="checkout ui-datepicker-target" placeholder="년/월/일">'
+'</div>'
+'</div>'
+'</div>'
+'<div class="col-md-3">'
+'<div>'
+'<label for="number_of_guests_21674" class="book-it__label"><span>숙박 인원</span></label>'
+'<div class="select select-block">'
+'<select id="number_of_guests_21674" name="number_of_guests">'
+'<option selected="selected" value="1">1</option>'
+'<option value="2">2</option>'
+'<option value="3">3</option>'
+'</select>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div>'
+'<button class="btn btn-primary btn-large btn-block" name="paying_go">'
+'<span>예약 요청</span>'
+'</button>'
+'<div class="bookit-message__container text-center text-muted">'
+'<small><span>"예약" 버튼을 클릭해도 대금이 바로 청구되지 않습니다.</span></small>'
+'</div>'
+'</div>'
+'<div class="hide">'
+'<button type="button" class="btn btn-primary btn-large btn-small btn-block">'
+'<span>호스트에게 연락하기</span>'
+'</button>'
+'</div>'
+'</div>'
+'</div>'
+'</form>'
+'</div>'
+'</div>'
 +'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+''
+'<div>'
+'<div>'
+'<div id="details" class="details-section webkit-render-fix">'
+'<div class="page-container-responsive">'
+'<div class="row">'
+'<div class="col-lg-8 js-details-column">'
+'<div class="space-8 space-top-8"><h4 class="space-4 text-center-sm"></h4>'
+'<div class="row row-condensed">'
+'<div class="contact-host-div col-12">'
+'<div>'
+'<button class="btn-link btn-link--bold" type="button">'
+'<span>호스트에게 연락하기</span>'
+'</button>'
+'</div>'
+'</div>'
+'</div>'
+'<hr>'
+'<div class="row">'
+'<div class="col-md-3 text-muted">'
+'<div><span>숙소</span></div>'
+'</div>'
+'<div class="col-md-9">'
+'<div class="row">'
+'<div class="col-md-6">'
+'<div>'
+'<span>숙박 가능 인원:</span>'
+'<span></span><strong>3</strong>'
+'</div>'
+'<div>'
+'<span>욕실:</span>'
+'<span> </span><strong>1</strong>'
+'</div>'
+'<div>'
+'<span>침실:</span>'
+'<span> </span><strong>1</strong>'
+'</div>'
+'<div>'
+'<span>침대:</span>'
+'<span> </span><strong>1</strong>'
+'</div>'
+'</div>'
+'<div class="col-md-6">'
+'<div><span>체크인:</span>'
+'<span> </span><strong>15:00 이후</strong>'
+'</div>'
+'<div>'
+'<span>체크아웃:</span>'
+'<span> </span><strong>10:00</strong>'
+'</div>'
+'<div>'
+'<span>집 유형:</span>'
+'<span> </span><strong>아파트</strong>'
+'</div>'
+'<div>'
+'<span>숙소 유형 :</span>'
+'<span> </span><strong>집 전체</strong>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="row">'
+'<div class="col-md-6">'
+'<strong><a href="#house-rules" class="react-house-rules-trigger" data-prevent-default="true"><span>숙소 이용규칙</span></a></strong>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<hr>'
+'<div class="row amenities">'
+'<div class="col-md-3 text-muted">'
+'<div>'
+'<span>시설</span>'
+'</div>'
+'</div>'
+'<div class="col-md-9 expandable expanded">'
+''
+'<div class="expandable-content expandable-content-full">'
+'<div class="row">'
+'<div class="col-sm-6">'
+'<div>'
+'<div class="space-1">'
+'<span><i class="icon h3 icon-meal"></i><span>&nbsp;&nbsp;&nbsp;</span></span>'
+'<span id="amenity-long-tooltip-trigger-8"><strong>부엌</strong></span>'
+'</div>'
+'</div>'
+'<div>'
+'<div class="space-1 text-muted">'
+'<span id="amenity-long-tooltip-trigger-40"><del>필수품목</del></span>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="col-sm-6">'
+'<div>'
+'<div class="space-1">'
+'<span><i class="icon h3 icon-tv"></i><span>&nbsp;&nbsp;&nbsp;</span></span>'
+'<span id="amenity-long-tooltip-trigger-1"><strong>TV</strong></span>'
+'</div>'
+'</div>'
+'<div>'
+'<div class="space-1 text-muted">'
+'<span id="amenity-long-tooltip-trigger-40"><del>필수품목</del></span>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<hr>'
+'<div class="row">'
+'<div class="col-md-3 text-muted">'
+'<div>'
+'<span>가격</span>'
+'</div>'
+'</div>'
+'<div class="col-md-9">'
+'<div class="row">'
+'<div class="col-md-6">'
+'<div>'
+'<span>추가 인원 요금 :</span>'
+'<span> </span><strong>추가요금 없음</strong>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<hr>'
+'<div class="row description" id="description">'
+'<div class="col-md-3 text-muted">'
+'<div>'
+'<span>설명</span>'
+'</div>'
+'</div>'
+'<div class="col-md-9">'
+'<div>'
+'<div class="react-expandable expanded">'
+'<div class="expandable-content expandable-content-long">'
+'<div>'
+'<p><span>Small 14 Unit condo on the Beach in N. Myrtle Beach.</span></p>'
+'<p><span>설명</span></p>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<hr>'
+'<div class="row react-house-rules" id="house-rules">'
+'<div class="col-md-3">'
+'<div class="text-muted">'
+'<span>숙소 이용규칙</span>'
+'</div>'
+'</div>'
+'<div class="col-md-9">'
+'<div class="structured_house_rules">'
+'<div class="row col-sm-12">'
+'<span>체크인은 15:00 이후입니다.</span>'
+'</div>'
+'<div class="row">'
+'<div class="col-sm-2">'
+'<hr class="structured_house_rules__hr">'
+'</div>'
+'</div>'
+'</div>'
+'<div>'
+'<div class="react-expandable expanded">'
+'<div class="expandable-content">'
+'<div>'
+'<p><span>Winter rates: $70.00 per night</span></p>'
+'</div>'
+'<div class="expandable-indicator"></div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<hr>'
+'<div class="row">'
+'<div class="col-md-3 text-muted">'
+'<div>'
+'<span>안전 기능</span>'
+'</div>'
+'</div>'
+'<div class="col-md-9">'
+'<div class="row">'
+'<div class="col-sm-6">'
+'<div>'
+'<div class="space-1">'
+'<span id="amenity-short-tooltip-trigger-35"><span>화재 감지기</span></span>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="col-sm-6">'
+'<div>'
+'<div class="space-1">'
+'<span id="amenity-short-tooltip-trigger-39"><span>소화기</span></span>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<hr>'
+'<div class="row">'
+'<div class="col-md-3 text-muted">'
+'<div>'
+'<span>예약 가능 여부</span>'
+'</div>'
+'</div>'
+'<div class="col-md-9">'
+'<div class="row">'
+'<div class="col-md-6">최소 숙박일 <strong>3일</strong>.</div>'
+'<div class="col-md-6">'
+'<a id="view-calendar" href="#"><strong><span>달력 보기</span></strong></a>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div></div>'
+'<div id="host-profile" class="room-section webkit-render-fix">'
+'<div class="page-container-responsive space-top-8 space-8">'
+'<div class="row">'
+'<div class="col-lg-8">'
+'<h4 class="space-2 text-center-sm"><span>호스트</span></h4>'
+'<hr class="space-4 space-top-2">'
+'<div class="row">'
+'<div class="col-md-3 text-center">'
+'<div class="media-photo-badge">'
+'<a href="#" class="media-photo media-round">'
+'<img alt="Donald" class="media-photo media-round" height="90" width="90" data-pin-nopin="true" src="web/resources/img/default.jpg" title="Donald"></a>'
+'</div>'
+'</div>'
+'<div class="col-md-9">'
+'<h3 class="space-1">Donald</h3>'
+'<div class="row row-condensed space-2">'
+'<div class="col-md-12 text-muted">'
+'<span>Freeport, 뉴욕, 미국</span>'
+'<span> · </span>'
+'<span>회원가입 : 2009년 11월</span>'
+'</div>'
+'</div>'
+'<div class="react-expandable expanded">'
+'<div class="expandable-content expandable-content-long">'
+'<div><p><span>자기소개</span></p></div>'
+'<div class="expandable-indicator"></div>'
+'</div>'
+'</div>'
+'<div>'
+'<span class="btn btn-primary btn-small"><span>호스트에게 연락하기</span></span>'
+'<div><noscript data-reactid=".1exo7crry0w.2.0.0.0.2.1.5.1.0"></noscript></div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div id="neighborhood" class="room-section">'
+'<div style="position:relative;" class="page-container-responsive">'
+'<div class="p3-location--map">'
+'<div class="panel location-panel"></div>'
+'<ul id="guidebook-recommendations" class="hide">'
+'<li class="user-image"><img alt="Donald" data-pin-nopin="true" height="90" src="${context }/resources/img/default.jpg" title="Donald" width="90"></li>'
+'</ul>'
+'<div id="hover-card" class="panel">'
+'<div class="panel-body">'
+'<div class="text-center">숙소 위치</div>'
+'<div class="text-center">'
+'<span class="listing-location"><span>노스 머틀 비치,</span><span>사우스 캐롤라이나,</span><span>미국</span></span>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>';
var CANCEL = '<div id="cancel_form" class="formbox2">'
+'<h2>예약취소</h2>'
+'<p class="m_b_5">* <span class="red">예약정보</span>를 잘 확인하여 취소하시기 바랍니다.</p>'
+'<table class="table table-striped">'
 +'<caption><h4 style="text-align:center">예약정보</h4></caption>'
+'<thead>'
+'<tr>'
+'<th scope="col">예약신청일</th>'
+'<th scope="col">이용기간</th>'
+'<th scope="col">예약장소</th>'
+'<th scope="col">취소</th>'
+'</tr>'
+'</thead>'
+'<tbody>'
+'<tr>'
+'<td colspan="10"><center>신청하신 내역이 없습니다.</center></td>'
+'</tr>'
+'</tbody>'
+'</table>';
var PAYING_FORM = '<main id="site-content" role="main" style="margin-top : 10%;">'
+'<div data-hypernova-key="p4flash_messagebundlejs"><span data-react-checksum="464588145"></span></div>'
+'<div id="main-view" class="main-view page-container-responsive space-top-md-6 space-md-6 space-top-lg-6 space-lg-6">'
+'<form action="/payments/create_booking_v2" method="post" id="checkout-form">'
+'<div class="row">'
+'<div class="col-sm-12 p4-error-header space-1">'
+'<div class="alert alert-with-icon alert-error alert-block hide space-lg-2 space-md-2" id="form-errors">'
+'<i class="icon alert-icon icon-alert-alt"></i>'
  +'<div class="h5 space-1 error-header">'
+'거의 끝났습니다!'
+'</div>'
+'<ul></ul>'
+'</div>'
+'<div class="alert alert-with-icon alert-success alert-block hide space-lg-2 space-md-2" id="coupon-success">'
+'<i class="icon alert-icon icon-star-circled"></i>'
+'<div class="h5 space-1 error-header">'
+'프로모션 요금이 적용되었습니다.'
+'</div>'
+'전체 숙박 요금에 프로모션을 적용했습니다. 이제 즐거운 여행을 하는 일만 남았네요!'
+'</div>'
+'<div class="alert alert-with-icon alert-error alert-block hide space-lg-2 space-md-2" id="server-error">'
+'<i class="icon alert-icon icon-alert-alt"></i>'
+'오류가 발생하여 요청이 접수되지 않았습니다. 에어비앤비 웹사이트가 점검 중이었거나 연결이 자동으로 중지되었을 수 있습니다. 다시 시도해 주세요.'
+'</div>'
+'<div class="alert alert-with-icon alert-error alert-block hide space-lg-2 space-md-2" id="verification-error">'
+'<i class="icon alert-icon icon-alert-alt"></i>'
+'회원님의 카드를 인증할 수 없습니다. 다른 카드로 시도해 보세요. 회원님의 카드에는 금액이 청구되지 않았습니다.'
+'</div>'
+'<div class="alert alert-with-icon alert-error alert-block hide space-lg-2 space-md-2" id="house-rules-error">'
+'<i class="icon alert-icon icon-alert-alt"></i>'
+'<div class="h5 space-1 error-header">'
+'숙소 이용규칙과 약관'
+'</div>'
+'<p>'
+'예약를 하려면, 숙소 이용규칙과 약관에 동의하세요.'
+'</p>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="row">'
+'<div class="col-md-5 col-md-push-7 space-lg-2 space-md-2 side-summary-container">'
+'<div data-hypernova-key="p4_sidebarbundlejs">'
+'<div class="summary-card col-center">'
+'<div class="background-cover summary-card__payments-listing-image" style="background-image:url();">'
+'</div>'
+'<div class="pull-right space-3 summary-card__host-profile-photo">'
+'<div class="media-photo media-round">'
+'<img class="summary-card__host-profile-photo-src" src="https://a2.muscache.com/im/pictures/531c686c-96ff-4d95-8806-bc3452a0e62b.jpg?aki_policy=profile_x_medium" alt="Chris">'
 +'</div>'
 +'</div>'
 +'<div class="panel">'
 +'<div class="panel-body">'
 +'<div class="text-muted space-2"><span>호스트: SangHo님</span>'
 +'</div>'
 +'<div class="sidebar-text-large">고급 스튜디오를 최저가에 @강남역 최고의 위치!!'
 +'</div>'
 +'<div class="hide-sm text-muted">'
 +'<ul class="list-layout summary-card__additional-details-list">'
 +'<li>집 전체</li>'
 +'<li><small><div class="star-rating-wrapper">'
 +'<div class="star-rating" content="4.5">'
 +'<div class="foreground">'
 +'<span><span><i class="icon-star icon icon-beach icon-star-big"></i><span> </span></span><span>'
 +'<i class="icon-star icon icon-beach icon-star-big"></i><span> </span></span><span><i class="icon-star icon icon-beach icon-star-big"></i><span> </span></span><span>'
 +'<i class="icon-star icon icon-beach icon-star-big"></i><span> </span></span><i class="icon-star-half icon icon-beach icon-star-big"></i></span>'
 +'</div>'
 +'<div class="background">'
 +'<span><span><i class="icon-star icon icon-light-gray icon-star-big"></i><span> </span></span><span><i class="icon-star icon icon-light-gray icon-star-big"></i>'
 +'<span> </span></span><span><i class="icon-star icon icon-light-gray icon-star-big"></i><span> </span></span><span><i class="icon-star icon icon-light-gray icon-star-big"></i>'
 +'<span> </span></span><span><i class="icon-star icon icon-light-gray icon-star-big"></i><span> </span></span></span>'
 +'</div>'
 +'</div>'
 +'<span> </span><span class="h6"><small><span>60</span></small></span>'
 +'</div>'
 +'</small>'
 +'</li>'
 +'<li class="hide-md"><span>후기 60개</span></li>'
 +'</ul>'
 +'<div>Gangnam-daero, Seocho-gu, 서울 137-072, 한국</div>'
 +'</div>'
 +'</div>'
 +'<div class="panel-body hide-sm">'
 +'<div class="row row-condensed">'
 +'<div class="col-sm-5">'
 +'<div class="text-muted space-bottom-2"><span>체크인</span>'
 +'</div><span>2016년 10월 13일</span>'
 +'</div>'
 +'<div class="col-sm-2 summary-card__check-in-icon">'
 +'<i class="icon icon-chevron-right icon-light-gray"></i>'
 +'</div>'
 +'<div class="col-sm-5">'
 +'<div class="text-muted space-bottom-2"><span>체크아웃</span>'
 +'</div><span>2016년 10월 14일</span>'
 +'</div>'
 +'</div>'
 +'</div>'
 +'<div class="panel-body hide-sm">'
 +'<table class="summary-card__billing-table">'
 +'<tbody>'
 +'<tr class="price-item">'
 +'<td><span>₩58036 x 1박</span><span>&nbsp;</span></td>'
 +'<td class="text-right price-item__price"><div><span>₩58036</span></div></td>'
 +'</tr>'
 +'</tbody>'
 +'</table>'
 +'</div>'
 +'<div class="panel-body hide-sm">'
 +'<span class="sidebar-text-large space-2 summary-card__total-price" tabindex="-1">'
 +'<table class="summary-card__billing-table">'
 +'<tbody>'
 +'<tr class="price-item">'
 +'<td><span>총합계</span><span>&nbsp;</span></td>'
 +'<td class="text-right price-item__price">'
 +'<div><span>₩78126</span><sup>KRW</sup></div>'
 +'</td>'
 +'</tr>'
 +'</tbody>'
 +'</table>'
 +'</span>'
 +'</div>'
 +'<div class="show-sm panel-body text-center"><a><span>요금 및 여행 요약 보기</span></a></div>'
 +'</div>'
 +'</div>'
 +'</div>'
+'<div class="pwp-summary-container"></div>'
+'</div>'
+'<div class="urgency-commitment-message col-md-7 col-md-pull-5 space-lg-4 space-md-4 space-sm-2">'
+'<div data-hypernova-key="p4_urgency_commitment_messagebundlejs">'
+'<div><span class="hide-sm">'
+'<div class="panel UrgencyCommitmentWrapper--expanded">'
+'<div class="panel-body">'
+'<div class="icon-background-container icon-rare-find-background">'
+'<div class="UrgencyCommitmentWrapper__text">'
+'<strong>흔치 않은 기회입니다.</strong>'
+'<div class="media space-top-1">Chris님의 숙소는 보통 예약이 가득 차있습니다.</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</span>'
+'<div class="show-sm"><a href="#" class="link-reset">'
+'<div class="panel UrgencyCommitmentWrapper--expanded">'
+'<div class="panel-body">'
+'<div class="icon-background-container icon-rare-find-background">'
+'<div class="UrgencyCommitmentWrapper__text">'
+'<strong>흔치 않은 기회입니다.</strong>'
+'<div class="media space-top-1">Chris님의 숙소는 보통 예약이 가득 차있습니다.</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div></a>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div id="content-container" class="summary-card-page-content col-md-7 col-md-pull-5">'
+'<div class="accordion-panel" data-panel-name="Payment">'
  +'<div id="payment-panel" class="accordion-panel__content accordion-panel-overflow text-lead accordion-panel--expanded">'
+'<div id="payment_selectors">'
+'<div>'
+'<div class="row space-4">'
+'<div class="col-sm-12"><span>호스트가 요청을 수락한 경우에만 비용이 청구됩니다. 호스트는 24시간 내로 요청을 수락 또는 거절해야 합니다.</span>'
+'</div>'
+'</div>'
+'<div>'
+'<div class="row space-4">'
+'<div class="col-6">'
+'<div>'
+'<label for="payment_country"><span>결제 국가</span></label>'
+'<div class="select select-block">'
+'<select name="payment_country">'
 +'<option selected="" value="KR">한국</option>'
+'</select>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div>'
+'<div class="row">'
+'<div class="col-sm-12">'
+'<label for="payment_type"><span>결제 방법</span></label>'
+'</div>'
+'</div>'
+'<div class="row space-4">'
+'<div class="col-md-6 col-sm-12">'
+'<div>'
+'<div class="select select-block">'
+'<select name="payment_type">'
+'<option selected="" value="0">신용카드</option>'
+'</select>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div>'
+'<div>'
+'<div>'
+'<div class="row space-4">'
+'<div class="col-12">'
+'<div><iframe name="payment-iframe" width="100%" height="206" frameborder="0" scrolling="no" seamless="" src="https://iframes.airbnbpayments.com/b559a9258b67d889f841daf72497323a8a21302d/pay.html?country=KR&amp;origin=https%3A%2F%2Fwww.airbnb.co.kr&amp;show_first_message_redesign=1"></iframe>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="row space-4">'
+'<div class="col-6">'
+'<div>'
+'<label for="credit_card[first_name]"><span>이름</span></label>'
+'<input name="credit_card[first_name]" type="text">'
+'</div>'
+'</div>'
+'<div class="col-6">'
+'<div>'
+'<label for="credit_card[last_name]"><span>성</span></label>'
+'<input name="credit_card[last_name]" type="text">'
+'</div>'
+'</div>'
+'</div>'
+'<div class="row space-4">'
+'<div class="col-4">'
+'<div>'
+'<label for="credit_card[zip]"><span>우편번호</span></label>'
+'<input name="credit_card[zip]" type="text">'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="accordion-style-checkout__section">'
+'<div>'
+'<div>'
+'<div class="text-lead">'
+'<div class="media-body text-rausch">에어비앤비는 게스트가 호스트와 협의하여 직접 계약을 체결할 수 있도록 해주는 플랫폼을 제공합니다. 숙박은 호스트가 게스트에게 제공하며, 에어비앤비는 호스트의 행위나 숙박을 감독하지 않습니다. 에어비앤비는 게스트와 호스트 사이에 체결되는 어떠한 계약의 당사자도 아니므로, 이에 관한 어떠한 책임도 지지 않습니다.</div>'
+'<div class="terms media">'
 +'<div class="media-body terms-media-body">'
 +'<label for="agrees-to-terms" class="va-container">'
  +'<div class="va-top accordion-checkbox">'
  +'<input id="agrees-to-terms" name="" type="checkbox" value="1">'
  +'</div>'
  +'<div class="va-top" id="agrees-to-terms-text">'
  +'<div><a href="#" class="house-rules-link" id="house-rules-modal-trigger">숙소 이용규칙</a>, <a href="/home/cancellation_policies#strict" class="cancel-policy-link" target="_blank">환불정책</a>, <a href="/terms/guest_refund_policy" class="refund_policy_link" target="_blank">게스트 환불 정책</a>에 동의합니다. 서비스 수수료를 포함하여 표시된 총액을 지불하는 것에도 동의합니다.</div>'
  +'</div>'
 +'</label>'
 +'</div>'
+'</div>'
+'</div>'
+'<div class="space-top-3">'
+'<div id="payment-form-submit-wrapper">'
+'<button class="btn btn-large btn-primary disabled" id=""><span>요청 보내기</span></button>'
+'</div>'
+'</div>'
+'<div class="hide">'
+'<div class="space-1">'
+'<div class="space-2 space-top-2 text-lead">'
+'<div>'
+'<div class="space-2 space-top-2"><h4><span>Chris님의 숙소를 예약하려면 신분증을 보여주세요.</span></h4><p class="text-muted"><span>호스트 Chris님은 예약 전에 에어비앤비에 정부 발행 신분증을 제출할 것을 요구합니다. 신분증 자체는 호스트에게 보이지 않으며, 본 인증은 신분증이 만료될 때까지 유효합니다.</span></p></div>'
+'<button type="button" class="btn btn-primary btn-large"><span>신분증 사진 촬영</span></button>'
 +'</div>'
 +'</div>'
 +'</div>'
 +'</div>'
 +'<div id="house-rules-modal" class="modal" role="dialog" aria-hidden="true" data-trigger="#house-rules-modal-trigger">'
 +'<div class="modal-table">'
 +'<div class="modal-cell">'
 +'<div class="modal-content">'
 +'<div class="panel-header house-rules-modal-label"><span>Chris님의 숙소 이용규칙</span><a href="#" class="panel-close" data-behavior="modal-close">×</a></div>'
 +'<div class="panel-body house-rules-modal-body">'
 +'<div class="expandable_house_rules">'
 +'<div class="structured_house_rules">'
 +'<div class="row col-sm-12"><span>흡연 금지</span></div>'
 +'<div class="row col-sm-12 space-top-1"><span>반려동물 동반에 적합하지 않음</span></div>'
 +'<div class="row col-sm-12 space-top-1"><span>파티나 이벤트 금지</span></div>'
 +'<div class="row col-sm-12 space-top-1"><span>체크인은 22:00 이후입니다.</span></div>'
 +'<div class="row">'
 +'<div class="col-sm-2"><hr class="structured_house_rules__hr"></div>'
 +'</div>'
 +'</div>'
 +'</div>'
 +'</div>'
 +'</div>'
 +'</div>'
 +'</div>'
 +'</div>'
 +'</div>'
+'</div>'
+'<div class="show-sm space-top-2">'
+'<div class="accordion-style-checkout__section">'
+'<div>'
+'<div>'
+'<div class="sidebar-text-large">'
+'<div><span>합계</span><span>&nbsp;</span><span>₩78126</span></div>'
+'</div><a href="#"><span>요금 및 여행 요약 보기</span></a></div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="modal" id="security-deposit-modal" role="dialog">'
+'<div class="modal-table">'
+'<div class="modal-cell">'
+'<div class="modal-content">'
+'<div class="panel-header">'
+'<a href="#" class="panel-close" data-behavior="modal-close">'
+'×'
+'<span class="screen-reader-only">'
+'보증금'
+'</span>'
+'</a>'
+'보증금'
+'</div>'
+'<div class="panel-body">'
+'<p>'
+'보증금은 체크인 하루 전에 회원님의 신용카드로 청구됩니다. 호스트가 문제를 제기하지 않는 경우, 체크아웃 48시간 후 청구 금액 전액이 취소됩니다.'
+'</p>'
+'<p>'
+'호스트가 문제를 제기할 경우에는, 에어비앤비에서 보증금의 지급을 유보하고 호스트와 게스트 양 당사자들로부터 추가 정보를 수집할 것입니다. 만약 호스트와 게스트 간에 합의가 이루어 지는 경우, 에어비앤비에서 해당 금액을 돌려드립니다. 주로 호스트가 피해 정도를 결정하지만, 에어비앤비는 모든 청구건들을 추적하여, 호스트가 보증금을 차지하기 위해 과도하게 청구를 하는 경향이 있다고 판단되면 이 호스트를 퇴출시킵니다.'
+'</p>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</main>';