var guide = (function() {
	var init = function(context) {
		onCreate();
	};
	var context = function() {
		return session.getContextPath();
	};
	var setContentView = function() {
	};
	var onCreate = function() {
		setContentView();
		$('#g_Seoul').click(function() {
			alert('가이드 서울 클릭 g_Seoul ');
			$.ajax({
				url : app.context() + '/guidebook/g_Seoul',
				success : function(data) {
					alert('가져온 데이타 값 {} : ' + data.message);
					if (data.message === "success") {
						$('#g_article').empty().html(g_Seoul);
					} else {
						alert('실패 {} : ');
					}
				},
				error : function(x, h, m) {
					alert('에러' + m);
				}
			});
		});
		$('#manage13').click(function() {
			alert('숙소관리 manage13 가이드북 ');
			$.ajax({
				url : app.context() + '/guidebook/manage13',
				success : function(data) {
					alert('가져온 데이타 값 {} : ' + data.message);
					if (data.message === "success") {
						$('#pub_article').empty().html(manage13);
					} else {
						alert('실패 {} : ');
					}
				},
				error : function(x, h, m) {
					alert('에러' + m);
				}
			});
		});
	};
	return {
		init : init,
		context : context,
		onCreate : onCreate,
		setContentView : setContentView
	}
})();

var manage13 =
		'<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">'
		+ '<link rel="stylesheet" href="${css}/hosting.css" />'
		+ '<style>'
		+ '#map {'
		+ 'height: 97%;'
		+ '}'
		+ '.controls {'
		+ 'background-color: #fff;'
		+ 'border-radius: 2px;'
		+ 'border: 1px solid transparent;'
		+ 'box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);'
		+ 'box-sizing: border-box;'
		+ 'font-family: Roboto;'
		+ 'font-size: 15px;'
		+ 'font-weight: 300;'
		+ 'height: 29px;'
		+ 'margin-left: 17px;'
		+ 'margin-top: 10px;'
		+ 'outline: none;'
		+ 'padding: 0 11px 0 13px;'
		+ 'text-overflow: ellipsis;'
		+ 'width: 400px;'
		+ '}'
		+ '.controls:focus {'
		+ 'border-color: #4d90fe;'
		+ '}'
		+ '</style>'
		+ '<div id="host_regist_div_page7">'
		+ '<div id="host_manage_detail_left1">'
		+ '<h5>호스팅</h5>'
		+ '<h6>'
		+ '<a href="${context}/hosting/manage_2">달력</a>'
		+ '</h6>'
		+ '<h6>'
		+ '<a href="${context}/hosting/manage_3">요금 설정</a>'
		+ '</h6>'
		+ '<h6>'
		+ '<a href="${context}/hosting/manage_4">예약</a>'
		+ '</h6>'
		+ '<h6>'
		+ '<a href="${context}/hosting/manage_5">체크인</a>'
		+ '</h6>'
		+ '<h6>'
		+ '<a href="${context}/hosting/manage_6">예약취소내역</a>'
		+ '</h6>'
		+ '<br>'
		+ '<h5>숙소</h5>'
		+ '<h6>'
		+ '<a href="${context}/hosting/manage_7">기본 설정</a>'
		+ '</h6>'
		+ '<h6>'
		+ '<a href="${context}/hosting/manage_8">설명</a>'
		+ '</h6>'
		+ '<h6>'
		+ '<a href="${context}/hosting/manage_9">위치</a>'
		+ '</h6>'
		+ '<h6>'
		+ '<a href="${context}/hosting/manage_10">편의시설</a>'
		+ '</h6>'
		+ '<h6>'
		+ '<a href="${context}/hosting/manage_11">사진</a>'
		+ '</h6>'
		+ '<h6>'
		+ '<a href="${context}/hosting/manage_12">숙소 안전</a>'
		+ '</h6>'
		+ '<br>'
		+ '<h5>게스트 자료</h5>'
		+ '<h6>'
		+ '<a href="${context}/hosting/manage_13">가이드북</a>'
		+ '</h6>'
		+ '<br>'
		+ '</div>'
		+ '<div id="host_manage_detail_right1">'
		+ '<div id="host_manage_detail_right2"'
		+ 'style="overflow: scroll; height: 820px;">'
		+ '<div id="host_manage_detail_right2_2">'
		+ '<h2>회원님이#도시이름#에서 좋아하는 것들을 소개해 주세요.</h2>'
		+ '<hr>'
		+ '<br>'
		+ '<div>'
		+ '<span>가장 좋아하는 음식점과 명소를 소개하는 가이드북을 만들어 보세요. 게스트가 이동 중에도 편리하게'
		+ '볼 수 있게요!</span>'
		+ '</div>'
		+ '<br>'
		+ '<div class="guidebook-form__sub-head-legal">'
		+ '<span>어디에 표시되나요?</span>'
		+ '<div class="guidebook-form__sub-head-legal">'
		+ '<a href="#" target="_blank"><span><span>가이드북'
		+ '인쇄하기 </span>»</span></a>'
		+ '</div>'
		+ '</div>'
		+ '<hr>'
		+ '<div>'
		+ '<h3>음식</h3>'
		+ '<hr>'
		+ '<div>'
		+ '제일 좋아하는 레스토랑, 베이커리, 커피숍이 어디인가요?'
		+ '<div>'
		+ '<input id="input" type="text"'
		+ 'placeholder="추천 장소...">'
		+ '</div>'
		+ '</div>'
		+ '</div>'
		+ '<hr>'
		+ '<div>'
		+ '<h3>바와 클럽</h3>'
		+ '<hr>'
		+ '<div>'
		+ '밤 시간에 여가를 즐길 때는 주로 어디로 가시나요?'
		+ '<div>'
		+ '<input id="input" type="text"'
		+ 'placeholder="추천 장소...">'
		+ '</div>'
		+ '</div>'
		+ '</div>'
		+ '<hr>'
		+ '<div>'
		+ '<h3>관광</h3>'
		+ '<hr>'
		+ '<div>'
		+ '놓쳐서는 안 될 상징적인 장소가 있나요?'
		+ '<div>'
		+ '<input id="input" type="text" placeholder="추천 장소...">'
		+ '</div>'
		+ '</div>'
		+ '</div>'
		+ '<hr>'
		+ '<div>'
		+ '<h3>공원 및 자연</h3>'
		+ '<hr>'
		+ '<div>'
		+ '자연을 느끼고 싶을 때 어디로 가세요?'
		+ '<div>'
		+ '<input id="input" type="text" placeholder="추천 장소...">'
		+ '</div>'
		+ '</div>'
		+ '</div>'
		+ '<hr>'
		+ '<div>'
		+ '<h3>예술과 문화</h3>'
		+ '<hr>'
		+ '<div>'
		+ '고유의 역사와 문화를 느낄 수 있는 장소를 추천한다면?'
		+ '<div>'
		+ '<input id="input" type="text" placeholder="추천 장소...">'
		+ '</div>'
		+ '</div>'
		+ '</div>'
		+ '<div>'
		+ '<hr>'
		+ '<h3>쇼핑</h3>'
		+ '<hr>'
		+ '<div>'
		+ '주변에 독특한 현지 가게들이 있나요?'
		+ '<div>'
		+ '<input id="input" type="text" placeholder="추천 장소...">'
		+ '</div>'
		+ '</div>'
		+ '</div>'
		+ '<div>'
		+ '<hr>'
		+ '<h3>생활 필수 서비스</h3>'
		+ '<hr>'
		+ '<div>'
		+ '식료품을 사거나 세탁물을 맡길 때, 어디로 가세요?'
		+ '<div>'
		+ '<input id="input" type="text" placeholder="추천 장소...">'
		+ '</div>'
		+ '</div>'
		+ '</div>'
		+ '<div>'
		+ '<hr>'
		+ '<h3>엔터테인먼트와 액티비티</h3>'
		+ '<hr>'
		+ '<div>'
		+ '놀거리를 즐길 수 있는 곳을 추천한다면?'
		+ '<div>'
		+ '<input id="input" type="text" placeholder="추천 장소...">'
		+ '</div>'
		+ '</div>'
		+ '</div>'
		+ '<div>'
		+ '<hr>'
		+ '<h3>교통편</h3>'
		+ '<hr>'
		+ '<div>'
		+ '주요 대중교통 수단은 무엇인가요? 주변에 자동차를 렌트할 수 있는 곳이 있나요?'
		+ '<div>'
		+ '<input id="input" type="text" placeholder="추천 장소...">'
		+ '</div>'
		+ '</div>'
		+ '</div>'
		+ '<div>'
		+ '<hr>'
		+ '<h3>기타</h3>'
		+ '<hr>'
		+ '<div>'
		+ '그 외 추천하고 싶은 장소가 있다면?'
		+ '<div>'
		+ '<input id="input" type="text" placeholder="추천 장소...">'
		+ '</div>'
		+ '</div>'
		+ '</div>'
		+ '</div>'
		+ '</div>'
		+ '<div id="host_manage_detail_right3">'
		+ '&nbsp;'
		+ '<div class="map-canvas" style="height: 100%; width: 100%;">'
		+ '<div'
		+ 'style="height: 95%; width: 100%; position: relative; margin-top: 5%;">'
		+ '<div id="map"></div>'
		+ '</div>'
		+ '</div>'
		+ '</div>'
		+ '</div>'
		+ '</div>'

var g_Seoul = '<link href="https://a1.muscache.com/airbnb/static/packages/common_o2.1-50a45a2f41dab81f98765e60188dc94c.css" media="all" rel="stylesheet" type="text/css">'
		+ '<link href="https://a1.muscache.com/airbnb/static/packages/manage_listing-5a21a78e524e212ada30b6a27fa6a498.css" media="screen" rel="stylesheet" type="text/css">'
		+ '<link href="https://a0.muscache.com/airbnb/static/packages/guidebook_new_guest_page-db43b7573ef62e14d129030f0166e840.css" media="screen" rel="stylesheet" type="text/css">'
		+ '<div class="guidebook-form">'
		+ '<div class="map-container guidebook-form__map-container">'
		+ '<div class="map-canvas" style="height: 100%; width: 100%;">'
		+ '<div style="height: 100%; width: 100%; position: relative; overflow: hidden;">'
		+ '<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d15047.120076241188!2d126.9363544769632!3d37.548764916285414!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sko!2skr!4v1472798528536"'
		+ 'width="100%" height="100%" frameborder="0" style="border: 0" allowfullscreen></iframe>'
		+ '</div>'
		+ '</div>'
		+ '</div>'
		+ ''
		+ '<div class="guidebook-new-guest-page__recommendation-container">'
		+ '<div class="guidebook-new-guest-page__image"'
		+ 'style="background-image: url(https://a2.muscache.com/ac/pictures/2a4e63c3-c981-4cbc-9c37-80a6ab3a9d24.jpg?interpolation=lanczos-none&amp;amp;size=x_large&amp;amp;output-format=progressive-jpeg&amp;amp;output-quality=70);"></div>'
		+ '<div class="panel">'
		+ '<div class="guidebook-new-guest-page__body">'
		+ '<div>'
		+ '<div>'
		+ '<h1 class="guidebook-new-guest-page__title">'
		+ '<span>서울 완전정복!</span>'
		+ '</h1>'
		+ '<h4 class="guidebook-new-guest-page__introduction">'
		+ '<span>돌아다닐 때 이것만 있으면 끝! 이 지역 에어비앤비 호스트가 추천하는 현지의 숨겨진 보석 같은'
		+ '장소들을 모은 가이드북입니다.</span></h4>'
		+ '<hr class="guidebook-new-guest-page__cut-off">'
		+ '<h3 class="guidebook-new-guest-page__best-of-best">'
		+ '<span>추천 장소 모음</span>'
		+ '</h3>'
		+ '</div>'
		+ '</div>'
		+ '<div class="guidebook-place-card-collection">'
		+ '<div class="guidebook-place-card-collection__item">'
		+ '<div class="guidebook-place-card-collection__scroll-anchor"></div>'
		+ '<div class="guidebook-place-card">'
		+ '<div class="guidebook-place-card__place-frame">'
		+ '<div>'
		+ '<p class="guidebook-place-card__number">'
		+ '<span>#</span>'
		+ '<span>1</span>'
		+ '</p>'
		+ '<a class="guidebook-place-card__save-button link-reset"">'
		+ '<i class="icon icon-size-2 icon-heart-alt"></i></a>'
		+ '</div>'
		+ '<h3 class="guidebook-place-card__title">서울의 명소</h3>'
		+ '<a href="#" class="guidebook-place-card__category"> 공원 및 자연</a>'
		+ '<a href="#" class="guidebook-place-card__category">공원</a>'
		+ '<div class="guidebook-place-card__other-highlights">'
		+ '<span class="guidebook-place-card__map-hours-and-website-group">'
		+ '<span class="guidebook-place-card__highlight">'
		+ '<a class="guidebook-place-card__link">'
		+ '<span>지도</span></a><span'
		+ 'class="guidebook-place-card__highlights-extra-padding">·</span></span>'
		+ '<span class="guidebook-place-card__highlight">'
		+ '<a class="guidebook-place-card__link">'
		+ '<span>영업 시간</span></a>'
		+ '<span class="guidebook-place-card__highlights-extra-padding">·</span></span>'
		+ '<span class="guidebook-place-card__highlight">'
		+ '<a href="#" target="_blank" class="guidebook-place-card__link">'
		+ '<span>웹사이트</span></a>'
		+ '<span class="guidebook-place-card__highlights-extra-padding">·</span></span></span>'
		+ '</div>'
		+ '</div>'
		+ '<div class="guidebook-place-recommendation__frame">'
		+ '<div>'
		+ '<p class="guidebook-place-recommendation__first-recommendation-title">'
		+ '<span>000명의 호스트가 추천</span>'
		+ '</p>'
		+ '<div style="display: none;">'
		+ '<button type="button"'
		+ 'class="guidebook-place-recommendation__recommendation-toggle-button">'
		+ '<span'
		+ 'class="guidebook-place-recommendation__recommendation-title">'
		+ '<span>호스트 추천 이유</span></span>'
		+ '<span>&nbsp;</span>'
		+ '<i class="icon icon-caret-up"></i>'
		+ '</button>'
		+ '</div>'
		+ '</div>'
		+ '<p class="guidebook-place-recommendation__description">'
		+ '<span> 호스트가 쓰는 코멘트가 이쪽에 표시</span>'
		+ '<a  class="guidebook-place-recommendation__link">'
		+ '<span>&nbsp;</span>'
		+ '<span>더 읽어보기</span></a>'
		+ '</p>'
		+ '<div>'
		+ '<div class="guidebook-place-recommendation__host-profile-image">'
		+ '<img'
		+ 'src="https://a1.muscache.com/im/users/27130439/profile_pic/1422933844/original.jpg?aki_policy=profile_small"'
		+ 'alt="Dougal" class="media-photo media-round"'
		+ 'style="height: 32px; width: 32px;">'
		+ '</div>'
		+ '<a href="#"'
		+ 'class="guidebook-place-recommendation__host-guidebook-link">'
		+ '<span>출처: Host(1)님의 가이드북</span></a>'
		+ '</div>'
		+ '</div>'
		+ '<div class="guidebook-place-recommendation__frame">'
		+ '<p class="guidebook-place-recommendation__description">'
		+ '<span>호스트가 쓰는 코멘트가 이쪽에 표시2</span>'
		+ '<a class="guidebook-place-recommendation__link">'
		+ '<span>&nbsp;</span>'
		+ '<span>더 읽어보기</span></a>'
		+ '</p>'
		+ '<div>'
		+ '<div class="guidebook-place-recommendation__host-profile-image">'
		+ '<img'
		+ 'src="https://a1.muscache.com/im/users/22662933/profile_pic/1422470091/original.jpg?aki_policy=profile_small"'
		+ 'alt="Leslie" class="media-photo media-round"'
		+ 'style="height: 32px; width: 32px;"'
		+ 'data-reactid=".1ze0k5z3k74.3.1.1.0.1.0:$150637.1.1:$1.2.0.0">'
		+ '</div>'
		+ '<a href="#"'
		+ 'class="guidebook-place-recommendation__host-guidebook-link">'
		+ '<span>출처: Host(2)님의 가이드북</span></a>'
		+ '</div>'
		+ '</div>'
		+ '<div class="guidebook-place-card-collection__pagination">'
		+ '<div class="pagination pagination-responsive">'
		+ '<ul class="list-unstyled">'
		+ '<li class="active">'
		+ '<a href="#">1</a></li>'
		+ '<li class="">'
		+ '<a href="#" rel="next">2</a></li>'
		+ '<li class="">'
		+ '<a href="#" rel="next">3</a></li>'
		+ '<li class="gap">'
		+ '<span class="gap">…</span></li>'
		+ '<li class="">'
		+ '<a href="#" rel="next">10</a></li>'
		+ '<li class="next next_page">'
		+ '<a href="#" rel="next">'
		+ '<span class="screen-reader-only">'
		+ '<span>다음</span></span>'
		+ '<i class="icon icon-caret-right"></i></a></li>'
		+ '</ul>'
		+ '</div>'
		+ '</div>'
		+ '</div>'
		+ '<div>'
		+ '<hr class="guidebook-new-guest-page__cut-off">'
		+ '<div class="guidebook-guest-page-footer__link-section">'
		+ '<div>'
		+ '<a href="#">'
		+ '<h4 class="guidebook-guest-page-footer__link-section-title">'
		+ '<span>서울에서 할 일 더 보기</span></h4></a>'
		+ '</div>'
		+ '<a  href="#"'
		+ 'class="guidebook-guest-page-footer__link-section-item">'
		+ '<span>서울에 있는 레스토랑</span></a>'
		+ '<a href="#"'
		+ 'class="guidebook-guest-page-footer__link-section-item">'
		+ '<span>서울에 있는 카페/커피숍</span></a>'
		+ '<a href="#"'
		+ 'class="guidebook-guest-page-footer__link-section-item">'
		+ '<span>서울에 있는 제과점</span></a>'
		+ '<a href="#"'
		+ 'class="guidebook-guest-page-footer__link-section-item">'
		+ '<span>서울에 있는 나이트클럽</span></a>'
		+ '<a href="#"'
		+ 'class="guidebook-guest-page-footer__link-section-item">'
		+ '<span>서울에 있는 바</span></a>'
		+ '<a href="#"'
		+ 'class="guidebook-guest-page-footer__link-section-item">'
		+ '<span>서울에 있는 흥미로운 장소</span></a>'
		+ '<a href="#"'
		+ 'class="guidebook-guest-page-footer__link-section-item">'
		+ '<span>서울에 있는 박물관</span></a>'
		+ '<a href="#"'
		+ 'class="guidebook-guest-page-footer__link-section-item">'
		+ '<span>서울에 있는 쇼핑몰</span></a>'
		+ '<a href="#"'
		+ 'class="guidebook-guest-page-footer__link-section-item">'
		+ '<span>서점</span></a>'
		+ '<a href="#"'
		+ 'class="guidebook-guest-page-footer__link-section-item">'
		+ '<span>영화관</span></a>'
		+ '</div></div>'
		+ '</div>'
		+ '</div>'
		+ '</div>' + '</div>' + '</div>' + '</div>'